
<div style="background: linear-gradient(120deg, #1a3a5c 0%, #2d6a9f 60%, #4a9eda 100%); padding: 28px 36px; border-radius: 14px; display: flex; align-items: center; gap: 28px; box-shadow: 0 4px 18px rgba(0,0,0,0.18);">
    <img src='Imagenes/iteso.jpg' style="height: 110px; border-radius: 8px; background: white; padding: 6px; flex-shrink: 0; box-shadow: 0 2px 8px rgba(0,0,0,0.2);"/>
    <div style="border-left: 2px solid rgba(255,255,255,0.4); padding-left: 28px;">
        <h1 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Propedéutico en Programación y Algoritmos para la Maestría en Ciencia de Datos</h1>
        <h3 style="margin: 0; color: rgba(255,255,255,0.8); font-weight: normal; font-size: 1.05em;">Módulo 3: Manipulación de Datos con la librería Pandas II</h3>
    </div>
</div>

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://numfocus.org/wp-content/uploads/2016/07/pandas-logo-300.png" width="400px" height="400px" />

> La clase pasada comenzamos a ver las funcionalidades de la librería [pandas](https://pandas.pydata.org/). Básicamente, aprendimos a cargar datos desde archivos `.csv`, aprendimos a seleccionar subcojuntos de estos datos mediante indización (obtener ciertas filas, o ciertas columnas, o ciertas filas y columnas determinadas). Finalmente, aprendimos a filtrar datos, es decir, a seleccionar registros de la base de datos que satisfagan cierta condición.

> Hoy nos enfocaremos a ver como reunir varias bases de datos que poseen información complementaria relativa a un mismo problema, para obtener una sola tabla con la información condensada.

Referencias:
- https://www.shanelynn.ie/merge-join-dataframes-python-pandas-index-1/
___

# 0. Motivación

En cualquier situación relacionada con ciencia de datos en la vida real, no pasarán más de 10 minutos sin que aparezca la necesidad de unir (`merge` o `join`) dos bases de datos complementarias para formar tu conjunto de datos para el análisis.

La unión de DataFrames es un proceso fundamental, que cualquier analista de datos en formación debe aprender. En esta clase aprenderemos cómo hacerlo, y en el camino responderemos las siguientes preguntas:

- ¿Qué son el `merge` o `join` de dos DataFrames?

- ¿Qué son `inner`, `outer`, `left` y `right` `joins`?

## Datos para la clase

En esta clase, seguiremos trabajando con los datos de la clase pasada:

En la carpeta "data" tenemos los archivos 

- "customers_data.csv": datos propios de los clientes de la empresa, 
- "sessions_data.csv": inicios de sesión de los clientes en la plataforma web de compras (similar a amazon),
- "transactions_data.csv": transacciones asociadas a cada inicio de sesión, y
- "products_data.csv": información de los productos. 

Podemos cargar cada uno de los archivos `.csv` como DataFrames de Pandas usando la función `read_csv()` de pandas, y examinar los contenidos de cada uno con el método `head()`.

In [1]:
# Importar pandas
import pandas as pd

In [2]:
# Cargar customers_data
customers = pd.read_csv('Data/customers_data.csv', index_col=[0])
customers

   customer_id  zip_code            join_date date_of_birth
0            1     60091  2011-04-17 10:48:33    1994-07-18
1            2     13244  2012-04-15 23:31:04    1986-08-18
2            3     13244  2011-08-13 15:42:34    2003-11-21
3            4     60091  2011-04-08 20:08:14    2006-08-15
4            5     60091  2010-07-17 05:27:50    1984-07-28

In [3]:
customers.shape

(5, 4)

In [4]:
# Cargar sessions_data
sesions = pd.read_csv('Data/sessions_data.csv', index_col=[0])
sesions

    session_id  customer_id   device        session_start
0            1            2  desktop  2014-01-01 00:00:00
1            2            5   mobile  2014-01-01 00:17:20
2            3            4   mobile  2014-01-01 00:28:10
3            4            1   mobile  2014-01-01 00:44:25
4            5            4   mobile  2014-01-01 01:11:30
5            6            1   tablet  2014-01-01 01:23:25
6            7            3   tablet  2014-01-01 01:39:40
7            8            4   tablet  2014-01-01 01:55:55
8            9            1  desktop  2014-01-01 02:15:25
9           10            2   tablet  2014-01-01 02:31:40
10          11            4   mobile  2014-01-01 02:47:55
11          12            4  desktop  2014-01-01 03:04:10
12          13            4   mobile  2014-01-01 03:15:00
13          14            1   tablet  2014-01-01 03:28:00
14          15            2  desktop  2014-01-01 03:41:00
15          16            2  desktop  2014-01-01 03:49:40
16          17            2   tablet  2014-01-01 04:00:30
17          18            1  desktop  2014-01-01 04:14:35
18          19            3  desktop  2014-01-01 04:27:35
19          20            5  desktop  2014-01-01 04:46:00
20          21            4  desktop  2014-01-01 05:02:15
21          22            4  desktop  2014-01-01 05:21:45
22          23            3  desktop  2014-01-01 05:32:35
23          24            5   tablet  2014-01-01 05:44:30
24          25            3  desktop  2014-01-01 05:59:40
25          26            1   tablet  2014-01-01 06:17:00
26          27            1   mobile  2014-01-01 06:34:20
27          28            5   mobile  2014-01-01 06:50:35
28          29            1   mobile  2014-01-01 07:10:05
29          30            5  desktop  2014-01-01 07:27:25
30          31            2   mobile  2014-01-01 07:42:35
31          32            5   mobile  2014-01-01 08:02:05
32          33            2   mobile  2014-01-01 08:10:45
33          34            3  desktop  2014-01-01 08:24:50
34          35            3   mobile  2014-01-01 08:44:20

In [13]:
sesions.head()

   session_id  customer_id   device        session_start
0           1            2  desktop  2014-01-01 00:00:00
1           2            5   mobile  2014-01-01 00:17:20
2           3            4   mobile  2014-01-01 00:28:10
3           4            1   mobile  2014-01-01 00:44:25
4           5            4   mobile  2014-01-01 01:11:30

In [ ]:
sesions['device'].unique() #regresa serie

<StringArray>
['desktop', 'mobile', 'tablet']
Length: 3, dtype: str

In [5]:
# Cargar transactions_data
transactions = pd.read_csv('Data/transactions_data.csv', index_col=[0])
transactions

     transaction_id  session_id     transaction_time  product_id  amount
0               298           1  2014-01-01 00:00:00           5  127.64
1                 2           1  2014-01-01 00:01:05           2  109.48
2               308           1  2014-01-01 00:02:10           3   95.06
3               116           1  2014-01-01 00:03:15           4   78.92
4               371           1  2014-01-01 00:04:20           3   31.54
..              ...         ...                  ...         ...     ...
495             112          35  2014-01-01 08:56:15           5   55.42
496             111          35  2014-01-01 08:57:20           3   34.87
497             276          35  2014-01-01 08:58:25           1   10.94
498             266          35  2014-01-01 08:59:30           5   19.86
499             203          35  2014-01-01 09:00:35           3  148.31

[500 rows x 5 columns]

In [15]:
transactions.session_id

0       1
1       1
2       1
3       1
4       1
       ..
495    35
496    35
497    35
498    35
499    35
Name: session_id, Length: 500, dtype: int64

In [ ]:
transactions.iloc[0,2] #regresa cadena de texto

'2014-01-01 00:00:00'

In [6]:
# Cargar products_data
products = pd.read_csv('Data/products_data.csv', index_col=[0])
products

   product_id brand
0           1     B
1           2     B
2           3     B
3           4     B
4           5     A

## Bonus: formato de fechas y horas

Como vimos la vez pasada, es relevante en general un correcto manejo de las fechas y horas en las bases de datos.

Lo primero que se tiene que hacer para un correcto manejo de las fechas (y horas) es identificar las columnas o variables que contienen fechas. Por ejemplo, de la tabla `customers_data`:

Lo que sigue, es especificarle a pandas el formato en que vienen esas fechas con la función `to_datetime()` de pandas

In [7]:
# Cargar customers_data
customers = pd.read_csv('Data/customers_data.csv', index_col=[0])
customers

   customer_id  zip_code            join_date date_of_birth
0            1     60091  2011-04-17 10:48:33    1994-07-18
1            2     13244  2012-04-15 23:31:04    1986-08-18
2            3     13244  2011-08-13 15:42:34    2003-11-21
3            4     60091  2011-04-08 20:08:14    2006-08-15
4            5     60091  2010-07-17 05:27:50    1984-07-28

In [18]:
# Ayuda en la función to_datetime
help(pd.to_datetime)

Help on function to_datetime in module pandas:

to_datetime(
    arg: DatetimeScalarOrArrayConvertible | DictConvertible,
    errors: DateTimeErrorChoices = 'raise',
    dayfirst: bool = False,
    yearfirst: bool = False,
    utc: bool = False,
    format: str | None = None,
    exact: bool | lib.NoDefault = <no_default>,
    unit: str | None = None,
    origin: str = 'unix',
    cache: bool = True
) -> DatetimeIndex | Series | DatetimeScalar | NaTType
    Convert argument to datetime.

    This function converts a scalar, array-like, :class:`Series` or
    :class:`DataFrame`/dict-like to a pandas datetime object.

    Parameters
    ----------
    arg : int, float, str, datetime, list, tuple, 1-d array, Series, DataFrame/dict-like
        The object to convert to a datetime. If a :class:`DataFrame` is provided, the
        method expects minimally the following columns: :const:`"year"`,
        :const:`"month"`, :const:`"day"`. The column "year"
        must be specified in 4-digit format.
    errors : {'raise', 'coerce'}, default 'raise'
        - If :const:`'raise'`, then invalid parsing will raise an exception.
        - If :const:`'coerce'`, then invalid parsing will be set as :const:`NaT`.
    dayfirst : bool, default False
        Specify a date parse order if `arg` is str or is list-like.
        If :const:`True`, parses dates with the day first, e.g. :const:`"10/11/12"`
        is parsed as :const:`2012-11-10`.

        .. warning::

            ``dayfirst=True`` is not strict, but will prefer to parse
            with day first.

    yearfirst : bool, default False
        Specify a date parse order if `arg` is str or is list-like.

        - If :const:`True` parses dates with the year first, e.g.
          :const:`"10/11/12"` is parsed as :const:`2010-11-12`.
        - If both `dayfirst` and `yearfirst` are :const:`True`, `yearfirst` is
          preceded (same as :mod:`dateutil`).

        .. warning::

            ``yearfirst=True`` is not strict, but will prefer to parse
            with year first.

    utc : bool, default False
        Control timezone-related parsing, localization and conversion.

        - If :const:`True`, the function *always* returns a timezone-aware
          UTC-localized :class:`Timestamp`, :class:`Series` or
          :class:`DatetimeIndex`. To do this, timezone-naive inputs are
          *localized* as UTC, while timezone-aware inputs are *converted* to UTC.

        - If :const:`False` (default), inputs will not be coerced to UTC.
          Timezone-naive inputs will remain naive, while timezone-aware ones
          will keep their time offsets. Limitations exist for mixed
          offsets (typically, daylight savings), see :ref:`Examples
          <to_datetime_tz_examples>` section for details.

        See also: pandas general documentation about `timezone conversion and
        localization
        <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
        #time-zone-handling>`_.

    format : str, default None
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. note::

            If a :class:`DataFrame` is passed, then `format` has no effect.

    exact : bool, default True
        Control how `format` is used:

        - If :const:`True`, require an exact `format` match.
        - If :const:`False`, allow the `format` to match anywhere in the target
          string.

        Cannot be used alongside ``format='ISO8601'`` or ``format='mixed'``.
    unit : str, default 'ns'
        The unit of the arg (D,s,ms,us,ns) denote the unit, which is an
        integer or float number. This will be based off the origin.
        Example, with ``unit='ms'`` and ``origin='unix'``, this would calculate
        the number of milliseconds to the unix epoch start.
    origin : scalar, default 'unix'
        Define the reference date. The numeric values would be parsed as number
        of units (defined by `unit`) since this reference date.

        - If :const:`'unix'` (or POSIX) time; origin is set to 1970-01-01.
        - If :const:`'julian'`, unit must be :const:`'D'`, and origin is set to
          beginning of Julian Calendar. Julian day number :const:`0` is assigned
          to the day starting at noon on January 1, 4713 BC.
        - If Timestamp convertible (Timestamp, dt.datetime, np.datetimt64 or date
          string), origin is set to Timestamp identified by origin.
        - If a float or integer, origin is the difference
          (in units determined by the ``unit`` argument) relative to 1970-01-01.
    cache : bool, default True
        If :const:`True`, use a cache of unique, converted dates to apply the
        datetime conversion. May produce significant speed-up when parsing
        duplicate date strings, especially ones with timezone offsets. The cache
        is only used when there are at least 50 values. The presence of
        out-of-bounds values will render the cache unusable and may slow down
        parsing.

    Returns
    -------
    datetime
        If parsing succeeded.
        Return type depends on input (types in parenthesis correspond to
        fallback in case of unsuccessful timezone or out-of-range timestamp
        parsing):

        - scalar: :class:`Timestamp` (or :class:`datetime.datetime`)
        - array-like: :class:`DatetimeIndex` (or :class:`Series` with
          :class:`object` dtype containing :class:`datetime.datetime`)
        - Series: :class:`Series` of :class:`datetime64` dtype (or
          :class:`Series` of :class:`object` dtype containing
          :class:`datetime.datetime`)
        - DataFrame: :class:`Series` of :class:`datetime64` dtype (or
          :class:`Series` of :class:`object` dtype containing
          :class:`datetime.datetime`)

    Raises
    ------
    ParserError
        When parsing a date from string fails.
    ValueError
        When another datetime conversion error happens. For example when one
        of 'year', 'month', day' columns is missing in a :class:`DataFrame`, or
        when a Timezone-aware :class:`datetime.datetime` is found in an array-like
        of mixed time offsets, and ``utc=False``, or when parsing datetimes
        with mixed time zones unless ``utc=True``. If parsing datetimes with mixed
        time zones, please specify ``utc=True``.

    See Also
    --------
    DataFrame.astype : Cast argument to a specified dtype.
    to_timedelta : Convert argument to timedelta.
    convert_dtypes : Convert dtypes.

    Notes
    -----

    Many input types are supported, and lead to different output types:

    - **scalars** can be int, float, str, datetime object (from stdlib :mod:`datetime`
      module or :mod:`numpy`). They are converted to :class:`Timestamp` when
      possible, otherwise they are converted to :class:`datetime.datetime`.
      None/NaN/null scalars are converted to :const:`NaT`.

    - **array-like** can contain int, float, str, datetime objects. They are
      converted to :class:`DatetimeIndex` when possible, otherwise they are
      converted to :class:`Index` with :class:`object` dtype, containing
      :class:`datetime.datetime`. None/NaN/null entries are converted to
      :const:`NaT` in both cases.

    - **Series** are converted to :class:`Series` with :class:`datetime64`
      dtype when possible, otherwise they are converted to :class:`Series` with
      :class:`object` dtype, containing :class:`datetime.datetime`. None/NaN/null
      entries are converted to :const:`NaT` in both cases.

    - **DataFrame/dict-like** are converted to :class:`Series` with
      :class:`datetime64` dtype. For each row a datetime is created from assembling
      the various dataframe columns. Column keys can be common abbreviations
      like ['year', 'month', 'day', 'minute', 'second', 'ms', 'us', 'ns']) or
      plurals of the same.

    The following causes are responsible for :class:`datetime.datetime` objects
    being returned (possibly inside an :class:`Index` or a :class:`Series` with
    :class:`object` dtype) instead of a proper pandas designated type
    (:class:`Timestamp`, :class:`DatetimeIndex` or :class:`Series`
    with :class:`datetime64` dtype):

    - when any input element is before :const:`Timestamp.min` or after
      :const:`Timestamp.max`, see `timestamp limitations
      <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
      #timeseries-timestamp-limits>`_.

    - when ``utc=False`` (default) and the input is an array-like or
      :class:`Series` containing mixed naive/aware datetime, or aware with mixed
      time offsets. Note that this happens in the (quite frequent) situation when
      the timezone has a daylight savings policy. In that case you may wish to
      use ``utc=True``.

    Examples
    --------

    **Handling various input formats**

    Assembling a datetime from multiple columns of a :class:`DataFrame`. The keys
    can be common abbreviations like ['year', 'month', 'day', 'minute', 'second',
    'ms', 'us', 'ns']) or plurals of the same

    >>> df = pd.DataFrame({"year": [2015, 2016], "month": [2, 3], "day": [4, 5]})
    >>> pd.to_datetime(df)
    0   2015-02-04
    1   2016-03-05
    dtype: datetime64[us]

    Using a unix epoch time

    >>> pd.to_datetime(1490195805, unit="s")
    Timestamp('2017-03-22 15:16:45')
    >>> pd.to_datetime(1490195805433502912, unit="ns")
    Timestamp('2017-03-22 15:16:45.433502912')

    .. warning:: For float arg, precision rounding might happen. To prevent
        unexpected behavior use a fixed-width exact type.

    Using a non-unix epoch origin

    >>> pd.to_datetime([1, 2, 3], unit="D", origin=pd.Timestamp("1960-01-01"))
    DatetimeIndex(['1960-01-02', '1960-01-03', '1960-01-04'],
                  dtype='datetime64[s]', freq=None)

    **Differences with strptime behavior**

    :const:`"%f"` will parse all the way up to nanoseconds.

    >>> pd.to_datetime("2018-10-26 12:00:00.0000000011", format="%Y-%m-%d %H:%M:%S.%f")
    Timestamp('2018-10-26 12:00:00.000000001')

    **Non-convertible date/times**

    Passing ``errors='coerce'`` will force an out-of-bounds date to :const:`NaT`,
    in addition to forcing non-dates (or non-parseable dates) to :const:`NaT`.

    >>> pd.to_datetime("invalid for Ymd", format="%Y%m%d", errors="coerce")
    NaT

    .. _to_datetime_tz_examples:

    **Timezones and time offsets**

    The default behaviour (``utc=False``) is as follows:

    - Timezone-naive inputs are converted to timezone-naive :class:`DatetimeIndex`:

    >>> pd.to_datetime(["2018-10-26 12:00:00", "2018-10-26 13:00:15"])
    DatetimeIndex(['2018-10-26 12:00:00', '2018-10-26 13:00:15'],
                  dtype='datetime64[us]', freq=None)

    - Timezone-aware inputs *with constant time offset* are converted to
      timezone-aware :class:`DatetimeIndex`:

    >>> pd.to_datetime(["2018-10-26 12:00 -0500", "2018-10-26 13:00 -0500"])
    DatetimeIndex(['2018-10-26 12:00:00-05:00', '2018-10-26 13:00:00-05:00'],
                  dtype='datetime64[us, UTC-05:00]', freq=None)

    - However, timezone-aware inputs *with mixed time offsets* (for example
      issued from a timezone with daylight savings, such as Europe/Paris)
      are **not successfully converted** to a :class:`DatetimeIndex`.
      Parsing datetimes with mixed time zones will raise a ValueError unless
      ``utc=True``:

    >>> pd.to_datetime(
    ...     ["2020-10-25 02:00 +0200", "2020-10-25 04:00 +0100"]
    ... )  # doctest: +SKIP
    ValueError: Mixed timezones detected. Pass utc=True in to_datetime
    or tz='UTC' in DatetimeIndex to convert to a common timezone.

    - To create a :class:`Series` with mixed offsets and ``object`` dtype, please use
      :meth:`Series.apply` and :func:`datetime.datetime.strptime`:

    >>> import datetime as dt
    >>> ser = pd.Series(["2020-10-25 02:00 +0200", "2020-10-25 04:00 +0100"])
    >>> ser.apply(lambda x: dt.datetime.strptime(x, "%Y-%m-%d %H:%M %z"))
    0    2020-10-25 02:00:00+02:00
    1    2020-10-25 04:00:00+01:00
    dtype: object

    - A mix of timezone-aware and timezone-naive inputs will also raise a ValueError
      unless ``utc=True``:

    >>> from datetime import datetime
    >>> pd.to_datetime(
    ...     ["2020-01-01 01:00:00-01:00", datetime(2020, 1, 1, 3, 0)]
    ... )  # doctest: +SKIP
    ValueError: Mixed timezones detected. Pass utc=True in to_datetime
    or tz='UTC' in DatetimeIndex to convert to a common timezone.

    |

    Setting ``utc=True`` solves most of the above issues:

    - Timezone-naive inputs are *localized* as UTC

    >>> pd.to_datetime(["2018-10-26 12:00", "2018-10-26 13:00"], utc=True)
    DatetimeIndex(['2018-10-26 12:00:00+00:00', '2018-10-26 13:00:00+00:00'],
                  dtype='datetime64[us, UTC]', freq=None)

    - Timezone-aware inputs are *converted* to UTC (the output represents the
      exact same datetime, but viewed from the UTC time offset `+00:00`).

    >>> pd.to_datetime(["2018-10-26 12:00 -0530", "2018-10-26 12:00 -0500"], utc=True)
    DatetimeIndex(['2018-10-26 17:30:00+00:00', '2018-10-26 17:00:00+00:00'],
                  dtype='datetime64[us, UTC]', freq=None)

    - Inputs can contain both string or datetime, the above
      rules still apply

    >>> pd.to_datetime(["2018-10-26 12:00", datetime(2020, 1, 1, 18)], utc=True)
    DatetimeIndex(['2018-10-26 12:00:00+00:00', '2020-01-01 18:00:00+00:00'],
                  dtype='datetime64[us, UTC]', freq=None)

In [ ]:
# Especificar el formato de fechas en la tabla customers_data

In [19]:
customers['join_date'] = pd.to_datetime(customers['join_date'], format='%Y-%m-%d %H:%M:%S', errors = 'coerce')
customers['join_date']

0   2011-04-17 10:48:33
1   2012-04-15 23:31:04
2   2011-08-13 15:42:34
3   2011-04-08 20:08:14
4   2010-07-17 05:27:50
Name: join_date, dtype: datetime64[us]

In [9]:
customers

   customer_id  zip_code           join_date date_of_birth
0            1     60091 2011-04-17 10:48:33    1994-07-18
1            2     13244 2012-04-15 23:31:04    1986-08-18
2            3     13244 2011-08-13 15:42:34    2003-11-21
3            4     60091 2011-04-08 20:08:14    2006-08-15
4            5     60091 2010-07-17 05:27:50    1984-07-28

In [10]:
customers['date_of_birth']=pd.to_datetime(customers['date_of_birth'], format='%Y-%m-%d', errors = 'coerce')
customers['date_of_birth']

0   1994-07-18
1   1986-08-18
2   2003-11-21
3   2006-08-15
4   1984-07-28
Name: date_of_birth, dtype: datetime64[us]

In [20]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   zip_code       5 non-null      int64
 2   join_date      5 non-null      datetime64[us]
 3   date_of_birth  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(2)
memory usage: 292.0 bytes

Hagan esto mismo para todas las tablas:

In [11]:
sesions.head()

   session_id  customer_id   device        session_start
0           1            2  desktop  2014-01-01 00:00:00
1           2            5   mobile  2014-01-01 00:17:20
2           3            4   mobile  2014-01-01 00:28:10
3           4            1   mobile  2014-01-01 00:44:25
4           5            4   mobile  2014-01-01 01:11:30

In [23]:
# Especificar el formato de fechas en la tabla customers
transactions['transaction_time'] = pd.to_datetime(transactions['transaction_time'], format='%Y-%m-%d %H:%M:%S', errors = 'coerce')
transactions['transaction_time']

0     2014-01-01 00:00:00
1     2014-01-01 00:01:05
2     2014-01-01 00:02:10
3     2014-01-01 00:03:15
4     2014-01-01 00:04:20
              ...
495   2014-01-01 08:56:15
496   2014-01-01 08:57:20
497   2014-01-01 08:58:25
498   2014-01-01 08:59:30
499   2014-01-01 09:00:35
Name: transaction_time, Length: 500, dtype: datetime64[us]

## Volviendo al problema ...

Hay columnas o variables que relacionan las tablas. Por ejemplo:

- Los clientes pueden iniciar sesión en la plataforma cuantas veces quieran. De manera que hay una relación uno a muchos entre las tablas "customers_data" y "sessions_data", mediante la variable "customer_id".

- Cuando se efectúa una transacción se supone que se está comprando un producto. Por lo tanto hay una relación uno a muchos entre las tablas "transactions_data"  y "products_data", mediante la variable "product_id".

## Problemas

Primero, quisieramos determinar cuál es el dispositivo preferido por zona.

Luego, quisiéramos determinar cuál es la marca preferida por zona.

Para resolver lo anterior necesitamos unir ("merge" o "join") nuestros datasets en uno solo para el análisis.

___
# 1. Uniendo dos DataFrames...

> “Merging” two datasets is the process of bringing two datasets together into one, and aligning the rows from each based on common attributes or columns.

Las palabras “merge” y “join” se usan indistintamente en Pandas, y en otros lenguajes como SQL y R. En Pandas, hay métodos separados “merge” y “join”, que realizan cosas similares (personalmente uso el método "merge"), y la función "merge".

Vamos a concentrarnos en el **primer problema**. En este escenario, necesitamos llevar a cabo los siguientes pasos:

- Para cada fila en el dataset `sessions_data`, debemos hacer una nueva columna que contenga el "zip_code" respectivo de cada cliente.
- Una vez hagamos esto, obtenemos la moda de los dispositivos para cada cliente.

**¿Podemos usar un ciclo?**

Claro que si. Se podría escribir un ciclo para esta tarea. Éste iría a través de cada fila en `sessions_data`, y a cada "user_id" asignar el valor de la nueva columna con la zona respectiva.

Sin embargo, usar ciclos haría nuestra tarea mucho más lenta y plagada de más código que el necesario que si se usara la función (método) `join()`.

De forma que, para estas situaciones, **nunca usar ciclos**.

Para ver cómo podemos hacer lo anterior, veamos la ayuda de la función `merge()` de pandas:

In [24]:
# Ayuda de merge()
help(pd.merge)

Help on function merge in module pandas:

merge(
    left: DataFrame | Series,
    right: DataFrame | Series,
    how: MergeHow = 'inner',
    on: IndexLabel | AnyArrayLike | None = None,
    left_on: IndexLabel | AnyArrayLike | None = None,
    right_on: IndexLabel | AnyArrayLike | None = None,
    left_index: bool = False,
    right_index: bool = False,
    sort: bool = False,
    suffixes: Suffixes = ('_x', '_y'),
    copy: bool | lib.NoDefault = <no_default>,
    indicator: str | bool = False,
    validate: str | None = None
) -> DataFrame
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    left : DataFrame or named Series
        First pandas object to merge.
    right : DataFrame or named Series
        Second pandas object to merge.
    how : {'left', 'right', 'outer', 'inner', 'cross', 'left_anti', 'right_anti},
        default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
        * left_anti: use only keys from left frame that are not in right frame, similar
          to SQL left anti join; preserve key order.
        * right_anti: use only keys from right frame that are not in left frame, similar
          to SQL right anti join; preserve key order.
    on : Hashable or a sequence of the previous
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : Hashable or a sequence of the previous, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : Hashable or a sequence of the previous, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default False
        This keyword is now ignored; changing its value will have no
        impact on the method.

        .. deprecated:: 3.0.0

            This keyword is ignored and will be removed in pandas 4.0. Since
            pandas 3.0, this method always returns a new object using a lazy
            copy mechanism that defers copies until necessary
            (Copy-on-Write). See the `user guide on Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            for more details.

    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame(
    ...     {"lkey": ["foo", "bar", "baz", "foo"], "value": [1, 2, 3, 5]}
    ... )
    >>> df2 = pd.DataFrame(
    ...     {"rkey": ["foo", "bar", "baz", "foo"], "value": [5, 6, 7, 8]}
    ... )
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on="lkey", right_on="rkey")
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on="lkey", right_on="rkey", suffixes=("_left", "_right"))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on="lkey", right_on="rkey", suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='str')

    >>> df1 = pd.DataFrame({"a": ["foo", "bar"], "b": [1, 2]})
    >>> df2 = pd.DataFrame({"a": ["foo", "baz"], "c": [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how="inner", on="a")
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how="left", on="a")
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({"left": ["foo", "bar"]})
    >>> df2 = pd.DataFrame({"right": [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how="cross")
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

Ahora, veamos como podemos añadir el código postal a la tabla `sessions_data`, usando la función `merge()` de pandas:

In [27]:
# Uso de la función merge()
# sessions_with_zip = pd.merge(left=sessions,
#                              right=customers[['customer_id', 'zip_code']]
#                              on="customer_id")
sesions_with_zip = pd.merge(left=sesions, right=customers[['customer_id', 'zip_code']], on = 'customer_id', how = 'inner')
sesions_with_zip

    session_id  customer_id   device       session_start  zip_code
0            1            2  desktop 2014-01-01 00:00:00     13244
1            2            5   mobile 2014-01-01 00:17:20     60091
2            3            4   mobile 2014-01-01 00:28:10     60091
3            4            1   mobile 2014-01-01 00:44:25     60091
4            5            4   mobile 2014-01-01 01:11:30     60091
5            6            1   tablet 2014-01-01 01:23:25     60091
6            7            3   tablet 2014-01-01 01:39:40     13244
7            8            4   tablet 2014-01-01 01:55:55     60091
8            9            1  desktop 2014-01-01 02:15:25     60091
9           10            2   tablet 2014-01-01 02:31:40     13244
10          11            4   mobile 2014-01-01 02:47:55     60091
11          12            4  desktop 2014-01-01 03:04:10     60091
12          13            4   mobile 2014-01-01 03:15:00     60091
13          14            1   tablet 2014-01-01 03:28:00     60091
14          15            2  desktop 2014-01-01 03:41:00     13244
15          16            2  desktop 2014-01-01 03:49:40     13244
16          17            2   tablet 2014-01-01 04:00:30     13244
17          18            1  desktop 2014-01-01 04:14:35     60091
18          19            3  desktop 2014-01-01 04:27:35     13244
19          20            5  desktop 2014-01-01 04:46:00     60091
20          21            4  desktop 2014-01-01 05:02:15     60091
21          22            4  desktop 2014-01-01 05:21:45     60091
22          23            3  desktop 2014-01-01 05:32:35     13244
23          24            5   tablet 2014-01-01 05:44:30     60091
24          25            3  desktop 2014-01-01 05:59:40     13244
25          26            1   tablet 2014-01-01 06:17:00     60091
26          27            1   mobile 2014-01-01 06:34:20     60091
27          28            5   mobile 2014-01-01 06:50:35     60091
28          29            1   mobile 2014-01-01 07:10:05     60091
29          30            5  desktop 2014-01-01 07:27:25     60091
30          31            2   mobile 2014-01-01 07:42:35     13244
31          32            5   mobile 2014-01-01 08:02:05     60091
32          33            2   mobile 2014-01-01 08:10:45     13244
33          34            3  desktop 2014-01-01 08:24:50     13244
34          35            3   mobile 2014-01-01 08:44:20     13244

In [25]:
sesions.columns

Index(['session_id', 'customer_id', 'device', 'session_start'], dtype='str')

La función `merge()` es el objetivo principal de esta clase. Básicamente, la operación de unir dos DataFrames hace lo siguiente: 

- toma el DataFrame de la izquierda (argumento left=), 
- el DataFrame de la derecha (argumento right=),
- la columna donde se va a unir (argumento on=), y
- la forma en que se va a unir (argumento how=).

La variable en común sobre la que se hace la unión está especificada en el argumento `on`.

Con este resultado, podemos filtrar por zona y luego obtener la moda.

In [28]:
# Obtener la moda por zona
sesions_with_zip.head()

   session_id  customer_id   device       session_start  zip_code
0           1            2  desktop 2014-01-01 00:00:00     13244
1           2            5   mobile 2014-01-01 00:17:20     60091
2           3            4   mobile 2014-01-01 00:28:10     60091
3           4            1   mobile 2014-01-01 00:44:25     60091
4           5            4   mobile 2014-01-01 01:11:30     60091

In [30]:
sesions_with_zip['zip_code'].unique()

array([13244, 60091])

In [33]:
sesions_with_zip[sesions_with_zip['zip_code'] == 13244]

    session_id  customer_id   device       session_start  zip_code
0            1            2  desktop 2014-01-01 00:00:00     13244
6            7            3   tablet 2014-01-01 01:39:40     13244
9           10            2   tablet 2014-01-01 02:31:40     13244
14          15            2  desktop 2014-01-01 03:41:00     13244
15          16            2  desktop 2014-01-01 03:49:40     13244
16          17            2   tablet 2014-01-01 04:00:30     13244
18          19            3  desktop 2014-01-01 04:27:35     13244
22          23            3  desktop 2014-01-01 05:32:35     13244
24          25            3  desktop 2014-01-01 05:59:40     13244
30          31            2   mobile 2014-01-01 07:42:35     13244
32          33            2   mobile 2014-01-01 08:10:45     13244
33          34            3  desktop 2014-01-01 08:24:50     13244
34          35            3   mobile 2014-01-01 08:44:20     13244

In [34]:
sesions_with_zip['zip_code'].unique

<bound method Series.unique of 0     13244
1     60091
2     60091
3     60091
4     60091
5     60091
6     13244
7     60091
8     60091
9     13244
10    60091
11    60091
12    60091
13    60091
14    13244
15    13244
16    13244
17    60091
18    13244
19    60091
20    60091
21    60091
22    13244
23    60091
24    13244
25    60091
26    60091
27    60091
28    60091
29    60091
30    13244
31    60091
32    13244
33    13244
34    13244
Name: zip_code, dtype: int64>

In [36]:
s_zipcode1 = sesions_with_zip[sesions_with_zip['zip_code'] == 13244]
s_zipcode1

    session_id  customer_id   device       session_start  zip_code
0            1            2  desktop 2014-01-01 00:00:00     13244
6            7            3   tablet 2014-01-01 01:39:40     13244
9           10            2   tablet 2014-01-01 02:31:40     13244
14          15            2  desktop 2014-01-01 03:41:00     13244
15          16            2  desktop 2014-01-01 03:49:40     13244
16          17            2   tablet 2014-01-01 04:00:30     13244
18          19            3  desktop 2014-01-01 04:27:35     13244
22          23            3  desktop 2014-01-01 05:32:35     13244
24          25            3  desktop 2014-01-01 05:59:40     13244
30          31            2   mobile 2014-01-01 07:42:35     13244
32          33            2   mobile 2014-01-01 08:10:45     13244
33          34            3  desktop 2014-01-01 08:24:50     13244
34          35            3   mobile 2014-01-01 08:44:20     13244

In [38]:
sesions_with_zip.loc[sesions_with_zip['zip_code'] == 13244, 'device'].value_counts()

device
desktop    7
tablet     3
mobile     3
Name: count, dtype: int64

In [39]:
sesions_with_zip.loc[sesions_with_zip['zip_code'] == 60091, 'device'].value_counts()

device
mobile     10
desktop     7
tablet      5
Name: count, dtype: int64

In [45]:
for zipcode in sesions_with_zip['zip_code'].unique():
    print(sesions_with_zip.loc[sesions_with_zip['zip_code'] == zipcode, 'device'].value_counts())

device
desktop    7
tablet     3
mobile     3
Name: count, dtype: int64
device
mobile     10
desktop     7
tablet      5
Name: count, dtype: int64

### Usando GroupBy

In [46]:
s_groupby = sesions_with_zip.groupby(by='zip_code')['device'].value_counts()

In [47]:
s_groupby

zip_code  device
13244     desktop     7
          tablet      3
          mobile      3
60091     mobile     10
          desktop     7
          tablet      5
Name: count, dtype: int64

In [48]:
type(s_groupby)

pandas.Series

### ¿Qué son los tipos de unión inner, left, right y outer?

En nuestro ejemplo, unimos `sessions` con `customers` sobre la columna "custumers_id". En este caso, en ambas tablas existían todos los posibles valores de "customers_id" (1, 2, 3, 4, 5).

¿Qué pasa si esta situación no se cumple?

Por ejemplo, realicemos los siguientes cambios artificiales:

In [50]:
sesions['customer_id'].unique()

array([2, 5, 4, 1, 3])

In [53]:
s_artificial = sesions[sesions['customer_id'] != 2]
s_artificial

    session_id  customer_id   device       session_start
1            2            5   mobile 2014-01-01 00:17:20
2            3            4   mobile 2014-01-01 00:28:10
3            4            1   mobile 2014-01-01 00:44:25
4            5            4   mobile 2014-01-01 01:11:30
5            6            1   tablet 2014-01-01 01:23:25
6            7            3   tablet 2014-01-01 01:39:40
7            8            4   tablet 2014-01-01 01:55:55
8            9            1  desktop 2014-01-01 02:15:25
10          11            4   mobile 2014-01-01 02:47:55
11          12            4  desktop 2014-01-01 03:04:10
12          13            4   mobile 2014-01-01 03:15:00
13          14            1   tablet 2014-01-01 03:28:00
17          18            1  desktop 2014-01-01 04:14:35
18          19            3  desktop 2014-01-01 04:27:35
19          20            5  desktop 2014-01-01 04:46:00
20          21            4  desktop 2014-01-01 05:02:15
21          22            4  desktop 2014-01-01 05:21:45
22          23            3  desktop 2014-01-01 05:32:35
23          24            5   tablet 2014-01-01 05:44:30
24          25            3  desktop 2014-01-01 05:59:40
25          26            1   tablet 2014-01-01 06:17:00
26          27            1   mobile 2014-01-01 06:34:20
27          28            5   mobile 2014-01-01 06:50:35
28          29            1   mobile 2014-01-01 07:10:05
29          30            5  desktop 2014-01-01 07:27:25
31          32            5   mobile 2014-01-01 08:02:05
33          34            3  desktop 2014-01-01 08:24:50
34          35            3   mobile 2014-01-01 08:44:20

In [56]:
s_artificial['customer_id'].unique()

array([5, 4, 1, 3])

In [58]:
c_art = customers[customers['customer_id'] != 5]
c_art

   customer_id  zip_code           join_date date_of_birth
0            1     60091 2011-04-17 10:48:33    1994-07-18
1            2     13244 2012-04-15 23:31:04    1986-08-18
2            3     13244 2011-08-13 15:42:34    2003-11-21
3            4     60091 2011-04-08 20:08:14    2006-08-15

Por defecto, la operación `merge()` de pandas actpua con un merge tipo "inner". Un "inner merge", guarda únicamente los valores comúnes (en la columna especificada en el argumento `on=`) de ambos DataFrames.

Por ejemplo:

Los otros comportamientos se pueden revisar mejor a través de ejemplos:

In [60]:
# left join
sesions_with_zip_art = pd.merge(left=s_artificial, right=c_art, on = 'customer_id', how = 'left')
sesions_with_zip_art.head()

,session_id,customer_id,device,session_start,zip_code,join_date,date_of_birth
0,2,5,mobile,2014-01-01 00:17:20,NaN,NaT,NaT
1,3,4,mobile,2014-01-01 00:28:10,60091.0,2011-04-08 20:08:14,2006-08-15
2,4,1,mobile,2014-01-01 00:44:25,60091.0,2011-04-17 10:48:33,1994-07-18
3,5,4,mobile,2014-01-01 01:11:30,60091.0,2011-04-08 20:08:14,2006-08-15
4,6,1,tablet,2014-01-01 01:23:25,60091.0,2011-04-17 10:48:33,1994-07-18

In [61]:
sesions_with_zip_art['customer_id'].unique()

array([5, 4, 1, 3])

In [68]:
# right join
sesions_with_zip_art = pd.merge(left=s_artificial, right=c_art, on = 'customer_id', how = 'right')
sesions_with_zip_art.head()

,session_id,customer_id,device,session_start,zip_code,join_date,date_of_birth
0,4.0,1,mobile,2014-01-01 00:44:25,60091,2011-04-17 10:48:33,1994-07-18
1,6.0,1,tablet,2014-01-01 01:23:25,60091,2011-04-17 10:48:33,1994-07-18
2,9.0,1,desktop,2014-01-01 02:15:25,60091,2011-04-17 10:48:33,1994-07-18
3,14.0,1,tablet,2014-01-01 03:28:00,60091,2011-04-17 10:48:33,1994-07-18
4,18.0,1,desktop,2014-01-01 04:14:35,60091,2011-04-17 10:48:33,1994-07-18

In [69]:
sesions_with_zip_art['customer_id'].unique()

array([1, 2, 3, 4])

In [70]:
# outer join
sesions_with_zip_art = pd.merge(left=s_artificial, right=c_art, on = 'customer_id', how = 'outer')
sesions_with_zip_art.head()

,session_id,customer_id,device,session_start,zip_code,join_date,date_of_birth
0,4.0,1,mobile,2014-01-01 00:44:25,60091.0,2011-04-17 10:48:33,1994-07-18
1,6.0,1,tablet,2014-01-01 01:23:25,60091.0,2011-04-17 10:48:33,1994-07-18
2,9.0,1,desktop,2014-01-01 02:15:25,60091.0,2011-04-17 10:48:33,1994-07-18
3,14.0,1,tablet,2014-01-01 03:28:00,60091.0,2011-04-17 10:48:33,1994-07-18
4,18.0,1,desktop,2014-01-01 04:14:35,60091.0,2011-04-17 10:48:33,1994-07-18

In [71]:
sesions_with_zip_art['customer_id'].unique()

array([1, 2, 3, 4, 5])

In [72]:
sesions_with_zip_art

,session_id,customer_id,device,session_start,zip_code,join_date,date_of_birth
0,4.0,1,mobile,2014-01-01 00:44:25,60091.0,2011-04-17 10:48:33,1994-07-18
1,6.0,1,tablet,2014-01-01 01:23:25,60091.0,2011-04-17 10:48:33,1994-07-18
2,9.0,1,desktop,2014-01-01 02:15:25,60091.0,2011-04-17 10:48:33,1994-07-18
3,14.0,1,tablet,2014-01-01 03:28:00,60091.0,2011-04-17 10:48:33,1994-07-18
4,18.0,1,desktop,2014-01-01 04:14:35,60091.0,2011-04-17 10:48:33,1994-07-18
5,26.0,1,tablet,2014-01-01 06:17:00,60091.0,2011-04-17 10:48:33,1994-07-18
6,27.0,1,mobile,2014-01-01 06:34:20,60091.0,2011-04-17 10:48:33,1994-07-18
7,29.0,1,mobile,2014-01-01 07:10:05,60091.0,2011-04-17 10:48:33,1994-07-18
8,NaN,2,NaN,NaT,13244.0,2012-04-15 23:31:04,1986-08-18
9,7.0,3,tablet,2014-01-01 01:39:40,13244.0,2011-08-13 15:42:34,2003-11-21
10,19.0,3,desktop,2014-01-01 04:27:35,13244.0,2011-08-13 15:42:34,2003-11-21
11,23.0,3,desktop,2014-01-01 05:32:35,13244.0,2011-08-13 15:42:34,2003-11-21
12,25.0,3,desktop,2014-01-01 05:59:40,13244.0,2011-08-13 15:42:34,2003-11-21
13,34.0,3,desktop,2014-01-01 08:24:50,13244.0,2011-08-13 15:42:34,2003-11-21
14,35.0,3,mobile,2014-01-01 08:44:20,13244.0,2011-08-13 15:42:34,2003-11-21
15,3.0,4,mobile,2014-01-01 00:28:10,60091.0,2011-04-08 20:08:14,2006-08-15
16,5.0,4,mobile,2014-01-01 01:11:30,60091.0,2011-04-08 20:08:14,2006-08-15
17,8.0,4,tablet,2014-01-01 01:55:55,60091.0,2011-04-08 20:08:14,2006-08-15
18,11.0,4,mobile,2014-01-01 02:47:55,60091.0,2011-04-08 20:08:14,2006-08-15
19,12.0,4,desktop,2014-01-01 03:04:10,60091.0,2011-04-08 20:08:14,2006-08-15
20,13.0,4,mobile,2014-01-01 03:15:00,60091.0,2011-04-08 20:08:14,2006-08-15
21,21.0,4,desktop,2014-01-01 05:02:15,60091.0,2011-04-08 20:08:14,2006-08-15
22,22.0,4,desktop,2014-01-01 05:21:45,60091.0,2011-04-08 20:08:14,2006-08-15
23,2.0,5,mobile,2014-01-01 00:17:20,NaN,NaT,NaT
24,20.0,5,desktop,2014-01-01 04:46:00,NaN,NaT,NaT
25,24.0,5,tablet,2014-01-01 05:44:30,NaN,NaT,NaT
26,28.0,5,mobile,2014-01-01 06:50:35,NaN,NaT,NaT
27,30.0,5,desktop,2014-01-01 07:27:25,NaN,NaT,NaT
28,32.0,5,mobile,2014-01-01 08:02:05,NaN,NaT,NaT

Estos comportamientos son muy intuitivos a partir de sus valores.

Así mismo, sus usos son muy intuitivos (lo sabrán cuando se enfrenten a problemas reales).

### Resolvamos el problema 2

Determinar cuál es la marca preferida por zona.

In [73]:
sesions_with_zip.head()

   session_id  customer_id   device       session_start  zip_code
0           1            2  desktop 2014-01-01 00:00:00     13244
1           2            5   mobile 2014-01-01 00:17:20     60091
2           3            4   mobile 2014-01-01 00:28:10     60091
3           4            1   mobile 2014-01-01 00:44:25     60091
4           5            4   mobile 2014-01-01 01:11:30     60091

In [74]:
products

   product_id brand
0           1     B
1           2     B
2           3     B
3           4     B
4           5     A

In [75]:
transactions_products = transactions.merge(right=products, on = 'product_id', how = 'inner')
transactions_products

     transaction_id  session_id    transaction_time  product_id  amount brand
0               298           1 2014-01-01 00:00:00           5  127.64     A
1                 2           1 2014-01-01 00:01:05           2  109.48     B
2               308           1 2014-01-01 00:02:10           3   95.06     B
3               116           1 2014-01-01 00:03:15           4   78.92     B
4               371           1 2014-01-01 00:04:20           3   31.54     B
..              ...         ...                 ...         ...     ...   ...
495             112          35 2014-01-01 08:56:15           5   55.42     A
496             111          35 2014-01-01 08:57:20           3   34.87     B
497             276          35 2014-01-01 08:58:25           1   10.94     B
498             266          35 2014-01-01 08:59:30           5   19.86     A
499             203          35 2014-01-01 09:00:35           3  148.31     B

[500 rows x 6 columns]

In [77]:
sesions_trans_prod = transactions_products.merge(right=sesions_with_zip, on = 'session_id', how = 'inner')
sesions_trans_prod

,transaction_id,session_id,transaction_time,product_id,amount,brand,customer_id,device,session_start,zip_code
0,298,1,2014-01-01 00:00:00,5,127.64,A,2,desktop,2014-01-01 00:00:00,13244
1,2,1,2014-01-01 00:01:05,2,109.48,B,2,desktop,2014-01-01 00:00:00,13244
2,308,1,2014-01-01 00:02:10,3,95.06,B,2,desktop,2014-01-01 00:00:00,13244
3,116,1,2014-01-01 00:03:15,4,78.92,B,2,desktop,2014-01-01 00:00:00,13244
4,371,1,2014-01-01 00:04:20,3,31.54,B,2,desktop,2014-01-01 00:00:00,13244
...,...,...,...,...,...,...,...,...,...,...
495,112,35,2014-01-01 08:56:15,5,55.42,A,3,mobile,2014-01-01 08:44:20,13244
496,111,35,2014-01-01 08:57:20,3,34.87,B,3,mobile,2014-01-01 08:44:20,13244
497,276,35,2014-01-01 08:58:25,1,10.94,B,3,mobile,2014-01-01 08:44:20,13244
498,266,35,2014-01-01 08:59:30,5,19.86,A,3,mobile,2014-01-01 08:44:20,13244
499,203,35,2014-01-01 09:00:35,3,148.31,B,3,mobile,2014-01-01 08:44:20,13244

In [79]:
x = sesions_trans_prod.groupby(by='zip_code')['brand'].value_counts()
x

zip_code  brand
13244     B        149
          A         37
60091     B        247
          A         67
Name: count, dtype: int64